listen_addresses = ['10.8.0.1:5353']
disabled_server_names = ['cs-de2', 'cs-nl', 'cs-fr', 'bcn', 'cisco', 'cisco-familyshield', 'cleanbrowsing-adult', 'cleanbrowsing-family', 'cleanbrowsing-security', 'adguard-dns-unfiltered']
max_clients = 250
ipv4_servers = true
ipv6_servers = false
dnscrypt_servers = true
doh_servers = false
require_dnssec = true
require_nolog = true
require_nofilter = true
force_tcp = false
timeout = 2000
lb_strategy = 'p2'
log_level = 2
log_file = '/var/log/dnscrypt-proxy.log'
cert_refresh_delay = 33
bootstrap_resolvers = ['10.8.0.1:53530']
forwarding_rules = 'forwarding-rules.txt'
ignore_system_dns = true
netprobe_timeout = 60
netprobe_address = '9.9.9.9:53'
log_files_max_size = 1
log_files_max_age = 1
log_files_max_backups = 7
block_ipv6 = true
cache = true
cache_size = 512
cache_min_ttl = 600
cache_max_ttl = 900
cache_neg_ttl = 60
[blocked_names]
blocked_names_file = 'blocklist.txt'
log_file = '/var/log/dnscrypt-proxy-blocked.log'
[sources]
  [sources.'public-resolvers']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v3/public-resolvers.md', 'https://ipv6.download.dnscrypt.info/resolvers-list/v3/public-resolvers.md', 'https://download.dnscrypt.net/resolvers-list/v3/public-resolvers.md']
  cache_file = 'public-resolvers.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''

  [sources.'relays']
  urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v3/relays.md', 'https://download.dnscrypt.info/resolvers-list/v3/relays.md', 'https://ipv6.download.dnscrypt.info/resolvers-list/v3/relays.md', 'https://download.dnscrypt.net/resolvers-list/v3/relays.md']
  cache_file = 'relays.md'
  minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
  refresh_delay = 72
  prefix = ''
  
[static]

# Anonymized DNS section.
# -----------------------
[anonymized_dns]

routes = [
   { server_name='*', via=['anon-cs-de2', 'anon-cs-nl', 'anon-cs-fr', 'anon-bcn'] }
]

skip_incompatible = true
